import type { StyleguideRule } from "../types.js";

/**
 * Overused vocabulary: words that are AI writing tells.
 * Sources: writewell SKILL.md, autonovel ANTI-SLOP.md
 *
 * Tier mapping:
 * - error: Kill-on-sight. Almost never natural. ("delve", "tapestry", "crucible")
 * - warning: Suspicious in clusters. Fine once, AI-sounding if repeated.
 * - info: Mild tells. Flag for author awareness only.
 */
export const overusedWords: StyleguideRule[] = [
  // -- Kill-on-sight (error) --
  {
    id: "word-delve",
    description: "Quintessential AI word — almost never used by human writers",
    severity: "error",
    category: "overused-word",
    pattern: "\\bdelve[sd]?\\b",
    suggestion: "Use 'explore', 'examine', 'look at', or remove.",
  },
  {
    id: "word-tapestry",
    description: "AI-favored metaphor for complexity",
    severity: "error",
    category: "overused-word",
    pattern: "\\btapestry\\b",
    suggestion: "Describe the complexity concretely.",
  },
  {
    id: "word-crucible",
    description: "AI-favored dramatic metaphor",
    severity: "error",
    category: "overused-word",
    pattern: "\\bcrucible\\b",
    suggestion: "Use a concrete description instead.",
  },
  {
    id: "word-underpinning",
    description: "AI-favored formal word",
    severity: "error",
    category: "overused-word",
    pattern: "\\bunderpinnings?\\b",
    suggestion: "Use 'basis', 'foundation', or describe directly.",
  },
  {
    id: "word-multifaceted",
    description: "AI-favored complexity descriptor",
    severity: "error",
    category: "overused-word",
    pattern: "\\bmultifaceted\\b",
    suggestion: "Describe the specific aspects instead.",
  },
  {
    id: "word-testament",
    description: "AI-favored significance marker",
    severity: "error",
    category: "overused-word",
    pattern: "\\btestament to\\b",
    suggestion: "Describe the evidence directly.",
  },
  {
    id: "word-embark",
    description: "AI-favored journey metaphor",
    severity: "error",
    category: "overused-word",
    pattern: "\\bembark(?:s|ed|ing)? (?:on|upon)\\b",
    suggestion: "Use 'start', 'begin', or describe the action.",
  },
  {
    id: "word-elucidate",
    description: "AI-favored formal alternative to 'explain'",
    severity: "error",
    category: "overused-word",
    pattern: "\\belucidate[sd]?\\b",
    suggestion: "Use 'explain', 'clarify', or 'show'.",
  },
  {
    id: "word-underscore",
    description: "AI-favored emphasis verb",
    severity: "error",
    category: "overused-word",
    pattern: "\\bunderscore[sd]?\\b",
    suggestion: "Use 'show', 'highlight', or 'emphasize'.",
  },
  {
    id: "word-interplay",
    description: "AI-favored relationship descriptor",
    severity: "error",
    category: "overused-word",
    pattern: "\\binterplay\\b",
    suggestion: "Use 'interaction', 'relationship', or be specific.",
  },
  {
    id: "word-juxtaposition",
    description: "AI-favored contrast word",
    severity: "error",
    category: "overused-word",
    pattern: "\\bjuxtaposition\\b",
    suggestion: "Use 'contrast' or describe the difference directly.",
  },
  {
    id: "word-palpable",
    description: "AI-favored intensity descriptor",
    severity: "error",
    category: "overused-word",
    pattern: "\\bpalpable\\b",
    suggestion: "Describe the sensation concretely.",
  },
  {
    id: "word-intricate",
    description: "AI-favored complexity descriptor",
    severity: "error",
    category: "overused-word",
    pattern: "\\bintricate(?:ly)?\\b",
    suggestion: "Describe the complexity with specifics.",
  },

  // -- Suspicious in clusters (warning) --
  {
    id: "word-landscape",
    description: "AI-favored metaphor, overused as 'the X landscape'",
    severity: "warning",
    category: "overused-word",
    pattern: "\\bthe \\w+ landscape\\b",
    suggestion: "Use a concrete term: 'market', 'field', 'industry', etc.",
  },
  {
    id: "word-leverage",
    description: "Overused in AI writing for 'use'",
    severity: "warning",
    category: "overused-word",
    pattern: "\\bleverage[sd]?\\b",
    suggestion: "Use 'use', 'apply', or a more specific verb.",
  },
  {
    id: "word-utilize",
    description: "Unnecessarily formal for 'use'",
    severity: "warning",
    category: "overused-word",
    pattern: "\\butilize[sd]?\\b",
    suggestion: "Use 'use'.",
  },
  {
    id: "word-navigate",
    description: "AI-favored metaphor for dealing with something",
    severity: "warning",
    category: "overused-word",
    pattern: "\\bnavigate[sd]?\\b",
    suggestion: "Use 'handle', 'manage', 'deal with', or be specific.",
  },
  {
    id: "word-robust",
    description: "Overused AI adjective",
    severity: "warning",
    category: "overused-word",
    pattern: "\\brobust\\b",
    suggestion: "Describe what makes it strong or reliable.",
  },
  {
    id: "word-pivotal",
    description: "AI-favored importance marker",
    severity: "warning",
    category: "overused-word",
    pattern: "\\bpivotal\\b",
    suggestion: "Use 'important', 'key', or explain why it matters.",
  },
  {
    id: "word-nuanced",
    description: "AI-favored sophistication marker",
    severity: "warning",
    category: "overused-word",
    pattern: "\\bnuanced\\b",
    suggestion: "Describe the specific subtleties.",
  },
  {
    id: "word-foster",
    description: "AI-favored growth verb",
    severity: "warning",
    category: "overused-word",
    pattern: "\\bfoster(?:s|ed|ing)?\\b",
    suggestion: "Use 'encourage', 'support', 'build', or be specific.",
  },
  {
    id: "word-bolster",
    description: "AI-favored support verb",
    severity: "warning",
    category: "overused-word",
    pattern: "\\bbolster(?:s|ed|ing)?\\b",
    suggestion: "Use 'support', 'strengthen', or be specific.",
  },
  {
    id: "word-streamline",
    description: "AI buzzword for simplification",
    severity: "warning",
    category: "overused-word",
    pattern: "\\bstreamline[sd]?\\b",
    suggestion: "Use 'simplify', 'speed up', or describe the improvement.",
  },
  {
    id: "word-comprehensive",
    description: "Overused AI scope descriptor",
    severity: "warning",
    category: "overused-word",
    pattern: "\\bcomprehensive\\b",
    suggestion: "Use 'complete', 'thorough', or describe what it covers.",
  },
  {
    id: "word-arguably",
    description: "AI hedging word",
    severity: "warning",
    category: "overused-word",
    pattern: "\\barguably\\b",
    suggestion: "State the argument directly or remove.",
  },
  {
    id: "word-moreover",
    description: "Overused AI transition",
    severity: "warning",
    category: "overused-word",
    pattern: "\\bmoreover\\b",
    suggestion: "Use 'also', 'and', or restructure.",
  },
  {
    id: "word-furthermore",
    description: "Overused AI transition",
    severity: "warning",
    category: "overused-word",
    pattern: "\\bfurthermore\\b",
    suggestion: "Use 'also', 'and', or restructure.",
  },
  {
    id: "word-nonetheless",
    description: "Overused AI transition",
    severity: "warning",
    category: "overused-word",
    pattern: "\\bnonetheless\\b",
    suggestion: "Use 'but', 'still', 'yet', or restructure.",
  },

  // -- Style awareness (info) --
  {
    id: "word-harness",
    description: "Sometimes AI-sounding, context dependent",
    severity: "info",
    category: "overused-word",
    pattern: "\\bharness(?:es|ed|ing)?\\b",
    suggestion: "Consider 'use', 'apply', or a more specific verb.",
  },
  {
    id: "word-empower",
    description: "Sometimes AI-sounding, context dependent",
    severity: "info",
    category: "overused-word",
    pattern: "\\bempower(?:s|ed|ing)?\\b",
    suggestion: "Consider 'enable', 'allow', or describe the capability.",
  },
  {
    id: "word-seamless",
    description: "Often AI-sounding hyperbole",
    severity: "info",
    category: "overused-word",
    pattern: "\\bseamless(?:ly)?\\b",
    suggestion: "Describe the actual user experience.",
  },
  {
    id: "word-myriad",
    description: "Sometimes AI-sounding, context dependent",
    severity: "info",
    category: "overused-word",
    pattern: "\\bmyriad\\b",
    suggestion: "Use 'many', 'numerous', or give a specific count.",
  },
];
